### PR TITLE
use if-then-else, infix notation for (=)/2, and format/2

### PR DESCRIPTION
**Pull request by triska**
Nota bene: An even better solution would be to decouple the
side-effects entirely from the actual logic! Strive for purity.

### CODE REVIEW

**Comment by alehander92** [comment]
Thanks! I am still new to Prolog and I often don't know the idiomatic way to write some things.

> side effect

Do you mean this snippet (the assoc list) or another part of the prolog code? (I am not entirely sure where is the side effect in the reformatter)

**Comment by triska** [comment]
Even if-then-else is not particularly idiomatic: The best way is to reason symbolically about your data. For example, you could use `v(Var)` to represent variables, and `a(Atom)` to represent atoms. You can perform an initial step where you introduce such a pure representation for all variables, and in all later parts of your program, you can simply write:

<pre>
any_predicate(v(Var))  :- ...
any_predicate(a(Atom)) :- ...
</pre>

This does not require if-then-else at all. Note that this even works in all directions, and also improves efficiency, because the Prolog engine can readily distinguish the cases by their first argument.

With **side-effects**, I mean everything that happens outside the realm of logic, in particular I/O such as currently with `format/2` and `write/1`. In my view, it would be best to cleanly separate the parts of your program that perform I/O from those that reason purely logically about your data.

And actually, the best way to perform output in Prolog is to let the toplevel do it for you. You can for example use a predicate:

<pre>
program_signature(P, S) :- ...
</pre>

that, given a program `P`, is supposed to derive the type signature `S`. No output at all is necessary from within your program: The Prolog toplevel will display the binding for&nbsp;`S` that shows the signature.

**Comment by alehander92** [comment]
> example, you could use v(Var) to represent variables, and a(Atom)

Awesome, that looks really nice! 

> everything that happens outside the realm of logic, in particular I/O

Ah, you are right, however I have forgotten several `write` in the library files only for debugging (yep, I found `trace`, but I still like print-debugging sometimes).
I use `format` mostly for string manipulation (~ template string), so I am not using it for I/O. I really use I/O only in the main predicates of my generated programs (I know the the toplevel thing is more prolog-ish, but I use the signatures in another Python script, so I wanted to have a way to communicate with the Prolog program)

**Comment by triska** [comment]
Suppose you have an entirely pure predicate which defines a clean relation (i.e., no I/O) between terms, then you can simply invoke Prolog with `-g "r(R), format("~w\n", [R]), halt.` to do the actual output when the program is invoked. There is hardly ever a reason to put such side-effects within your program.

Also, in SWI-Prolog, check out the **graphical tracer**, available with

```
?- gtrace, your_goal.
```

I hope this helps!

**Pull request merged**
